"""This file contains all program constants"""
# Constants describing windows
WINDOW_MAIN_MENU = 100
WINDOW_PRACTISE = 200
WINDOW_TEST = 300
WINDOW_STATS = 400
WINDOW_QMANAGER = 500
WINDOW_USERS = 600
WINDOW_TOPICS = 700
WINDOW_QUIT_PROGRAM = 900
WINDOW_EXTRACTOR = 100

# Constants for window events
EVENT_VIEW_ITEMS = 1
EVENT_ADD_ITEM = 2
EVENT_EDIT_ITEM = 3
EVENT_DELETE_ITEM = 4
EVENT_CHANGE_ITEM_STATUS = 5
EVENT_SAVE_ITEMS = 9
EVENT_EXTRACTOR = 10

#colors
COLOR_HEADER = "\033[92m"
COLOR_INPUT = "\033[93m"
COLOR_WARNING = "\033[91m"
COLOR_NORMAL = "\033[00m"

# other constants
FLAG_ENABLED = 1
FLAG_DISABLED = 0
REC_STATUS_DELETED = "Deleted"
REC_STATUS_ACTIVE = ""
REC_STATUS_NEW = "New"
REC_STATUS_UPDATED = "Updated"
META_FILE_DATA_IDX_FILENAME = 0
META_FILE_DATA_IDX_MAXID = 1
META_FILE_DATA_IDX_TIMESTAMP = 2
META_FILE_DATA_IDX_ITEM = 3
USER_TYPE_USER = "user"
USER_TYPE_ADMIN = "admin"
QUESTION_TYPE_FREE = "Free"
QUESTION_TYPE_MULTIPLE_CHOICE = "Multiple choice"
EDIT_MODE_NEW = "new"
EDIT_MODE_EDIT = "edit"


# Program defaults
MINIMUM_NUMBER_OF_ENABLED_ITEMS = 5
DEFAULT_TEST_CSVFILE = "Test bed"
USER_CSVFILE_NAME = "users"
RESULTS_FILENAME = "Data/results.txt"
CSV_FILE_DELIMITER = ";"
DEBUG_FLAG = False
